DROP TABLE IF EXISTS WEIGHTS;
DROP TABLE IF EXISTS NUTRIENT_DATA;
DROP TABLE IF EXISTS FOOD_DESCRIPTION;
DROP TABLE IF EXISTS FOOD_GROUP_DESCRIPTION;
DROP TABLE IF EXISTS NUTRIENT_DEFINITION;

CREATE TABLE FOOD_GROUP_DESCRIPTION (
  FdGrp_Cd   INTEGER(4)  NOT NULL,
  FdGrp_Desc VARCHAR(60) NOT NULL,
  PRIMARY KEY (FdGrp_Cd)
);

CREATE TABLE FOOD_DESCRIPTION (
  NBD_No      INTEGER(5)   NOT NULL,
  FdGrp_Cd    INTEGER(4)   NOT NULL,
  Long_Desc   VARCHAR(200) NOT NULL,
  Shrt_Desc   VARCHAR(60)  NOT NULL,
  ComName     VARCHAR(100),
  ManufacName VARCHAR(65),
  Survey      VARCHAR(1),
  Ref_Desc    VARCHAR(135),
  Refuse      DECIMAL(2),
  SciName     VARCHAR(65),
  N_Factor    DECIMAL(4, 2),
  Pro_Factor  DECIMAL(4, 2),
  Fat_Factor  DECIMAL(4, 2),
  CHO_Factor  DECIMAL(4, 2),
  PRIMARY KEY (NBD_No),
  FOREIGN KEY (FdGrp_Cd) REFERENCES FOOD_GROUP_DESCRIPTION (FdGrp_Cd)
);
CREATE TABLE NUTRIENT_DEFINITION (
  Nutr_No  INTEGER(3)  NOT NULL,
  Units    VARCHAR(7)  NOT NULL,
  TagName  VARCHAR(20),
  NutrDesc VARCHAR(60) NOT NULL,
  Num_Dec  INTEGER(1)  NOT NULL,
  SR_Order DECIMAL(6)  NOT NULL,
  PRIMARY KEY (Nutr_No)
);

CREATE TABLE NUTRIENT_DATA (
  Nutr_No       INTEGER(3)     NOT NULL,
  NDB_No        INTEGER(5)     NOT NULL,
  Nuts_Val      DECIMAL(10, 3) NOT NULL,
  Num_Data_Pts  DECIMAL(5, 0)  NOT NULL,
  Std_Error     DECIMAL(8, 3),
  Src_Cd        VARCHAR(2)     NOT NULL,
  Deriv_Cd      VARCHAR(4),
  Ref_NDB_No    VARCHAR(5),
  Add_Nutr_Mark VARCHAR(1),
  Num_Studies   INTEGER(2),
  Min_Val       DECIMAL(10, 3),
  Max_Val       DECIMAL(10, 3),
  DF            INTEGER(4),
  Low_EB        DECIMAL(10, 3),
  Up_EB         DECIMAL(10, 3),
  Stat_cmt      VARCHAR(10),
  AddModDate    VARCHAR(10),
  CC            VARCHAR(1),
  PRIMARY KEY (Nutr_No, NDB_No),
  FOREIGN KEY (NDB_No) REFERENCES NUTRIENT_DEFINITION (Nutr_No),
  FOREIGN KEY (Nutr_No) REFERENCES FOOD_DESCRIPTION (NBD_No)
);

CREATE TABLE WEIGHTS (
  NDB_No       INTEGER(5),
  Seq          INTEGER(2),
  Amount       DECIMAL(5, 3),
  Msre_Desc    VARCHAR(84),
  Gm_Wgt       DECIMAL(7, 1),
  Num_Data_Pts DECIMAL(3),
  Std_Dev      DECIMAL(7, 3),
  PRIMARY KEY (NDB_No, Seq),
  FOREIGN KEY (NDB_No) REFERENCES FOOD_DESCRIPTION (NBD_No)
);