SELECT FdGrp_Desc
FROM FOOD_GROUP_DESCRIPTION;

SELECT FdGrp_Desc
FROM FOOD_GROUP_DESCRIPTION
WHERE FdGrp_Desc LIKE '%cheese%';

SELECT Long_Desc
FROM FOOD_DESCRIPTION
WHERE Long_Desc LIKE '%yogurt%';

SELECT *
FROM (
    NUTRIENT_DEFINITION
    NATURAL JOIN NUTRIENT_DATA
)